title: FAQ
description: A starter template for a Jeykll site using the Just the Docs theme!
# theme: just-the-docs
remote_theme: "just-the-docs/just-the-docs"
url: https://suss-vli.github.io/faq/

aux_links:
  VLI: http://suss-vli.github.io

markdown: kramdown